### ISSUE TITLE
Depracted php?

### ISSUE THREAD

**Issue by mickkahn** [MegaphoneJon/org.cpehn.subscriptionhistory#4]
I reported to SE https://civicrm.stackexchange.com/questions/39794/warning-message-from-cron that I've started getting the following warning from my cron job and I think its triggered by a recent automatic upgrade to php 7.4.

Deprecated: Array and string offset access syntax with curly braces is deprecated in /home/customer/www/crm.coma.org/public_html/wp-content/uploads/civicrm/ext/org.cpehn.subscriptionhistory-master/subscriptionhistory.civix.php on line 149+

Not sure which cron job is executing this code or why.

Cheers,
Mick

**Comment by MegaphoneJon** [comment]
I just pushed an update.  

This change needs to happen on pretty much every extension written between about 2013 and 2020 - I've done it on all my extensions I'm currently using, but this slipped through because none of my clients are using it.

**Comment by mickkahn** [comment]
Thanks - that cured it, but as you suspected allows a warning from another extension to show up!

**Comment by MegaphoneJon** [comment]
If you look at my latest commit, it only affects `subscriptionhistory.civix.php`.  This is "boilerplate" that gets auto-generated.  If you want to fix this yourself on other extensions, you can review my most recent change and make the equivalent change to `extensionname.civix.php` on the other extension(s).  It should be the same line numbers and everything.

**Comment by mickkahn** [comment]
I was going to try and do just that, but looking at the diff for your file there are 278 additions and 103 deletions, so don't think I could replicate that. Its autogenerated with civix and I don't think I could do that (and certainly don't know how to). I'll live with it for now!
